[theme]
base                = "dark"
backgroundColor     = "#0a0a0f"
secondaryBackgroundColor = "#111118"
textColor           = "#f8fafc"
primaryColor        = "#f59e0b"
font                = "sans serif"

[server]
headless            = true
runOnSave           = true
fileWatcherType     = "none"

[browser]
gatherUsageStats    = false